### PR TITLE
restructured dashboard files, added cards, looking to resizing charts

### PR DESCRIPTION
**Pull request by omgitsmiles**
- Created dashboard folder to store charts and cards for the banking data.
- Changed color of the cards, looking at maybe using a smaller size.
- Looking into resizing googles charts.

### CODE REVIEW

**Review by jgrimes86 — CHANGES_REQUESTED** [review]
The SavingsCard components should be moved below TransactionChart so that the spending donut chart is the first visual at the top of the page.

What is the SavingsCard function intended to be?  Should they be linked to a Plaid balance request for savings or checking accounts?

**Comment by omgitsmiles** [comment]
Moved the chart to top.

Still getting the black bar for PlaidButton.

I'm open to connect to SavingsCards to the plaid connected savings and checkings account if you want to use it to display that data.

**Review by jgrimes86 — APPROVED** [review]
I don't know why, but it's working on my local version.  Maybe go ahead and merge it, let Peyton merge her branch, and then see about re-initializing the database again?

I do like the idea of showing account balances in the cards.  Although our list of to-dos is increasing as the deadline approaches.

**Comment by omgitsmiles** [comment]
Sounds good, if we run out of time with no ideas of implementation of cards, removing it wouldn't be a big deal.

**Pull request merged**
